### ISSUE TITLE
Multiple paths having the same operationId results in only one event source

### ISSUE THREAD

**Issue by Jaystified** [AKIRA-MIYAKE/serverless-import-swagger#28]
For example:

```yaml
paths:
  /aaa:
    get:
      operationId: fooBar
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
  /bbb:
    get:
      operationId: fooBar
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
```
Which results in:

```yaml
  fooBar:
    handler: "handler.fooBar"
    events:
    - http:
        path: "/api/v1/bbb"
        method: "get"
        integration: "lambda-proxy"
```

One of the event sources becomes "lost".

**Comment by exoego** [comment]
Unfortunately, `operationId` can not be duplicated.

> operationId is an optional unique string used to identify an operation.
> If provided, these IDs must be unique among all operations described in your API.
> https://swagger.io/docs/specification/paths-and-operations/

If we want attach serveral API paths (`http` event) to single Lambda, we should alias each paths like `fooBar` and `fooBarAlias1` or alike.

**Comment by Jaystified** [comment]
So it is a spec issue, then.
